version: '3.8'

services:
  # Apache Web Server with PHP
  web:
    build:
      context: ./docker/apache
      dockerfile: Dockerfile
    container_name: krishighor_web
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=krishighor
      - DB_USER=krishighor_user
      - DB_PASS=krishighor_pass
    depends_on:
      - db
    restart: unless-stopped

  # MySQL Database
  db:
    image: mysql:8.0
    container_name: krishighor_db
    environment:
      MYSQL_DATABASE: krishighor
      MYSQL_USER: krishighor_user
      MYSQL_PASSWORD: krishighor_pass
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data:
